stages:
  - stage : build
    jobs: 
    - job: buildpackaage
      pool: 
        vmImage: 'Ubuntu-18.04'
      continueOnError: true
      
      variables:
      - group: test
      - name: docker_repository
        value: 'devopstraining1990/parking'

      steps: 
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      
      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'
        
      - task: Docker@2
        inputs:
           containerRegistry: 'DockerServiceConnection'
           repository: $(docker_repository)
           command: 'buildAndPush'
           Dockerfile: 'Dockerfile'





